version: '3'
# ref: https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
    web:
        build: .
#        image: webapp:testtag
        container_name: name0
        ports:
            - "5000:8080"
        # for live code-update.
        volumes:
            - ./web:/app

#    db:
#        image: "mysql"
#        environment:
#            MYSQL_ROOT_PASSWORD: password
#        volumes:
#            - db-data:/foo 

volumes:
    db-data:
